# Generated by Django 3.0.5 on 2020-08-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Moderate'), ('D', 'Difficult')], default='E', max_length=1)),
                ('length', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('elevation_change', models.IntegerField(blank=True)),
                ('brief_description', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oregon_hikers_link', models.URLField(blank=True)),
            ],
        ),
    ]
