# Generated by Django 3.0.5 on 2020-09-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_auto_20200918_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='thumbnail_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
